### ISSUE TITLE
Include a "discontinued" graphic or label for each watch in "Install" page

### ISSUE THREAD

**Issue by jcstaudt** [AsteroidOS/asteroidos.org#47]
For newcomers that don't already have a smartwatch and are viewing the `Install` page, it is challenging to quickly find a supported/recommended watch to purchase.

One improvement that could easily check the last box is to add either a label or a graphic corresponding to each of the supported watches to indicate whether or not they are discontinued products. These indicators could be updated periodically (every few months?) to ensure that they remain generally accurate.

**Comment by FlorentRevest** [comment]
I believe that all of the supported watches are already discontinued :)

**Comment by Machin-Shin** [comment]
This is an old issue I know, but one idea would be to add a "recommended" by some of the better supported watches maybe? That would make it easy for someone to identify what watch to shop for if they just want a working watch. 

My only worry would be that we don't want to end up with everyone all using just one or two models because you risk loosing out on someone jumping on one of the less supported models and working to bring it up.

**Comment by FlorentRevest** [comment]
The original bug was about watches that are discontinued products (by their manufacturers) and afaik this is the case for most watches anyway so all the watches would need a label.

I don't like the idea of tagging watches as "discontinued" because most readers would probably think that AsteroidOS discontinued support for the watch. We never intend to drop support for any watch. Sometimes something blows up (like on tetra) but the intention is never to discontinue support for a watch.

Machin-Shin you propose that we have a label for the "recommended watches" to distinguish them for some which have a worse support but this is already the case with the three stars next to each watch. They indicate whether the watch has really good support (only bass and sturgeon have it, and they are the ones we always recommend) medium support (most watches) or bad support (tetra). I feel this avoid the risk in your comment, people who just want something that works get a bass or a sturgeon, people who already have one of the other watch and want to try Asteroid understand that it is either mostly supported (2 stars) or badly supported (1 star) and needs extra work.
